# Change these first
owner: weweb-team # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: WeWeb Dashboard
    url: https://dashboard.weweb.io/
    icon: https://status.weweb.io/weweb-logo-icon-white.svg
    slug: weweb-dashboard
  - name: WeWeb Editor
    url: https://editor.weweb.io/
    icon: https://status.weweb.io/weweb-logo-icon-white.svg
    slug: weweb-editor
  - name: WeWeb Published Websites (weweb-preview.io domain)
    url: https://b67796af-1e4a-4265-9be2-72dcf41d8a78.weweb-preview.io/
    icon: https://status.weweb.io/weweb-logo-icon-white.svg
    slug: weweb-published-no-domain
  - name: WeWeb Published Websites (Custom domain)
    url: https://health-check.weweb.io
    icon: https://status.weweb.io/weweb-logo-icon-white.svg
    slug: weweb-published-custom-domain
  - name: Xano (third-party)
    url: https://app.xano.com/
    slug: xano
  - name: Supabase (third-party)
    url: https://supabase.com/dashboard/org
    slug: supabase
    
i18n:
  footer: <a href="https://status.supabase.com/" target="_blanck">View Supabase status page</a><br>[WeWeb](https://weweb.io) status page, powered by [Upptime](https://upptime.js.org)
  liveStatus: System status
  allSystemsOperational: "All systems are operational 🟢"

status-website:
  theme: dark
  favicon: https://status.weweb.io/weweb-logo-icon-white.svg
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.weweb.io
  # baseUrl: /your-repo-name
  logoUrl: https://status.weweb.io/weweb-logo-wordmark-white.svg
  name: ""
  introTitle: ""
  introMessage: ""
  navbar:
  links:
    - rel: stylesheet
      href: https://status.weweb.io/style.css
  scripts:
    - src: https://status.weweb.io/onload.js


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
