# Change these first
owner: weweb-team # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: WeWeb Dashboard
    url: https://dashboard.weweb.io/
    icon: https://cdn.prod.website-files.com/62e9199d4976608473849e5a/67fd2d8f6fbee43ca082876d_weweb-favicon-32.png
  - name: WeWeb Editor
    url: https://editor.weweb.io/
    icon: https://cdn.prod.website-files.com/62e9199d4976608473849e5a/67fd2d8f6fbee43ca082876d_weweb-favicon-32.png
  - name: WeWeb Published Websites (Weweb domain)
    url: https://b67796af-1e4a-4265-9be2-72dcf41d8a78.weweb-preview.io/
    icon: https://cdn.prod.website-files.com/62e9199d4976608473849e5a/67fd2d8f6fbee43ca082876d_weweb-favicon-32.png
  - name: WeWeb Published Websites (Custom domain)
    url: https://health-check.weweb.io
    icon: https://cdn.prod.website-files.com/62e9199d4976608473849e5a/67fd2d8f6fbee43ca082876d_weweb-favicon-32.png
  - name: Xano (third-party)
    url: https://app.xano.com/
  - name: Supabase (third-party)
    url: https://supabase.com/dashboard/org

status-website:
  favicon: https://cdn.prod.website-files.com/62e9199d4976608473849e5a/67fd2d8f6fbee43ca082876d_weweb-favicon-32.png
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.weweb.io
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.prod.website-files.com/62e9199d4976608473849e5a/683dd4bf5096e2fe24c314b8_weweb-logo-wordmark-white-p-500.png
  name: Status Page
  introTitle: "This is the official **WeWeb** WIP status page."
  introMessage: IntroMessage
  navbar:
    - title: Status
      href: /
    - title: WeWeb
      href: https://weweb.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
